# Generated by Django 6.0.6 on 2026-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_matricula', models.CharField(max_length=20, unique=True)),
                ('categoria', models.CharField(choices=[('A', 'Categoria A - Motociclos'), ('B', 'Categoria B - Ligeiros'), ('C', 'Categoria C - Pesados'), ('D', 'Categoria D - Transporte Colectivo')], max_length=2)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspenso', 'Suspenso'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='activo', max_length=20)),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
    ]
