# Generated by Django 6.0.6 on 2026-06-29 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exames', '0001_initial'),
        ('instrutores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='instrutores.instrutor'),
        ),
    ]
