# Generated by Django 6.0.6 on 2026-06-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('combustivel', 'Combustível'), ('manutencao', 'Manutenção de Viaturas'), ('renda', 'Renda'), ('agua_luz', 'Água e Luz'), ('material', 'Material Didáctico'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('comprovativo', models.FileField(blank=True, null=True, upload_to='comprovativos/')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='SalarioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Salário',
                'verbose_name_plural': 'Salários',
            },
        ),
    ]
