# Generated by Django 6.0.6 on 2026-06-29 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_funcionario', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('data_contratacao', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instrutor', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Instrutor',
                'verbose_name_plural': 'Instrutores',
            },
        ),
    ]
